name: codemention
description: Mentions people who subscribe to file changes on pull requests
author: Toby Hsieh

inputs:
  githubToken:
    required: true
    description: GitHub API token

runs:
  using: composite
  steps:
    # Copying the action into the workspace makes things more convenient
    # because some things don't work outside the workspace (actions/setup-node
    # resolves the node-version-file input relative to the workspace; hashFiles
    # only works on files inside the workspace).
    - run: cp -r ${{ github.action_path }} codemention
      shell: bash
    - uses: actions/setup-node@v6
      with:
        node-version-file: codemention/.node-version
        package-manager-cache: false
    - uses: actions/cache@v5
      id: cache-node-modules
      with:
        path: codemention/node_modules
        key: codemention-npm-${{ hashFiles('codemention/package-lock.json') }}
    - run: npm ci
      working-directory: codemention
      shell: bash
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
    - run: npm run build
      working-directory: codemention
      shell: bash
    - run: node run.js
      working-directory: codemention
      shell: bash
      env:
        INPUT_GITHUBTOKEN: "${{ inputs.githubToken }}"
