name: codemention
description: Mentions people who subscribe to file changes on pull requests
author: Toby Hsieh

inputs:
  githubToken:
    required: true
    description: GitHub API token

runs:
  using: composite
  steps:
    - name: Copy action into workspace
      run: |
        [ "$(realpath "$GITHUB_ACTION_PATH")" = "$(realpath "$GITHUB_WORKSPACE")" ] || cp -r "${GITHUB_ACTION_PATH}/." .
      shell: bash
    - name: Install dependencies
      uses: ./populate-cache
    - run: npm run build
      shell: bash
    - run: node run.js
      shell: bash
      env:
        INPUT_GITHUBTOKEN: "${{ inputs.githubToken }}"

branding:
  icon: at-sign
  color: green
