# This GitHub action populates the dependency cache. This is a standalone
# action so it can be used to populate the cache for the main/default branch.
# Due to cache restrictions
# (https://docs.github.com/en/actions/reference/workflows-and-actions/dependency-caching#restrictions-for-accessing-a-cache),
# a pull request typically cannot save a cache that any other pull request can
# access.

name: 'codemention: populate cache'
description: Populates the dependency cache for codemention

runs:
  using: composite
  steps:
    # Copying the action into the workspace makes things more convenient
    # because some things don't work outside the workspace (actions/setup-node
    # resolves the node-version-file input relative to the workspace; hashFiles
    # only works on files inside the workspace).
    - name: Copy action into workspace
      # If this action is called by the main action (to install dependencies),
      # then action.yml should exist because the action already copied itself
      # to the workspace.
      run: |
        [ -f action.yml ] || cp -r "${GITHUB_ACTION_PATH}/../." .
      shell: bash
    - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version-file: .node-version
        package-manager-cache: false
    - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      id: cache-node-modules
      with:
        path: node_modules
        key: codemention-npm-${{ hashFiles('.node-version', 'package-lock.json') }}
    - run: npm ci
      shell: bash
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
